export const BRAZILIAN_BANKS = [
  'BANCO DO BRASIL S.A.', 'BANCO BRADESCO S.A.', 'ITAÚ UNIBANCO S.A.', 'CAIXA ECONOMICA FEDERAL', 'BANCO SANTANDER (BRASIL) S.A.',
  'BANCO BTG PACTUAL S.A.', 'BANCO SAFRA S.A.', 'BANCO PAN S.A.', 'BANCO INTER S.A.', 'BANCO C6 S.A.',
  'BANCO MERCANTIL DO BRASIL S.A.', 'BANCO ORIGINAL S.A.', 'BANCO MODAL S.A.', 'BANCO NEON S.A.', 'BANCO BMG S.A.',
  'BANCO XP S.A.', 'BANCO SICOOB S.A.', 'BANCO SICREDI S.A.', 'BANCO DAYCOVAL S.A.', 'BANCO SOFISA S.A.',
  'PICPAY SERVICOS S.A.', 'STONE PAGAMENTOS S.A.', 'MERCADO PAGO INSTITUICAO DE PAGAMENTO LTDA',
  'BANCO RENDIMENTO S.A.', 'BANCO ABC BRASIL S.A.', 'BANCO CREFISA S.A.',
  'BANCO FIBRA S.A.'
];

export const MENSAGENS_INICIAIS: { texto: string; genero: 'female' | 'male' }[] = [
  // Masculino - padrão equalizado para todos os valores
  { texto: "fiz o de [VALOR] ta no nome de [NOME]", genero: 'male' },
  { texto: "mandei [VALOR] agora ta no nome de [NOME]", genero: 'male' },
  { texto: "pronto fiz [VALOR] no nome de [NOME]", genero: 'male' },
  { texto: "ja mandei [VALOR] ta no nome do [NOME]", genero: 'male' },
  { texto: "fiz o de [VALOR] confere no nome de [NOME]", genero: 'male' },
  { texto: "ta feito [VALOR] no nome de [NOME]", genero: 'male' },
  { texto: "mandei [VALOR] pode ver no nome de [NOME]", genero: 'male' },
  { texto: "opa fiz [VALOR] ta no nome de [NOME]", genero: 'male' },
  { texto: "ja ta la [VALOR] no nome de [NOME]", genero: 'male' },
  { texto: "transferi [VALOR] ta no nome de [NOME]", genero: 'male' },
  { texto: "mandei [VALOR] no pix confere la", genero: 'male' },
  { texto: "feito [VALOR] no nome de [NOME]", genero: 'male' },
  { texto: "ja ta la o [VALOR] no nome de [NOME]", genero: 'male' },
  { texto: "enviei [VALOR] no nome de [NOME]", genero: 'male' },
  { texto: "fiz o pix de [VALOR] ta no nome de [NOME]", genero: 'male' },
  // Feminino - padrão equalizado para todos os valores
  { texto: "moço fiz o de [VALOR] ta no nome de [NOME]", genero: 'female' },
  { texto: "oi mandei [VALOR] no nome de [NOME] pode olhar", genero: 'female' },
  { texto: "fiz o pix de [VALOR] ta no nome de [NOME] 🙏", genero: 'female' },
  { texto: "acabei de mandar [VALOR] no nome de [NOME]", genero: 'female' },
  { texto: "enviei [VALOR] agora no nome de [NOME]", genero: 'female' },
  { texto: "moço mandei [VALOR] no nome de [NOME]", genero: 'female' },
  { texto: "ta feito [VALOR] no nome de [NOME] 😊", genero: 'female' },
  { texto: "ja foi [VALOR] no nome de [NOME]", genero: 'female' },
  { texto: "prontinho fiz [VALOR] no nome de [NOME]", genero: 'female' },
  { texto: "mandei [VALOR] rapidinho ta no nome de [NOME]", genero: 'female' },
  { texto: "moço ja ta la [VALOR] no nome de [NOME]", genero: 'female' },
  { texto: "mandei [VALOR] no pix pode conferir", genero: 'female' },
  { texto: "feito [VALOR] no nome de [NOME] 😊", genero: 'female' },
  { texto: "enviei [VALOR] ta no nome de [NOME]", genero: 'female' },
  { texto: "fiz o [VALOR] e ta no nome de [NOME]", genero: 'female' },
];

export const RESPOSTAS_ESPERA: { texto: string; genero: 'female' | 'male' }[] = [
  { texto: "ok, to esperando 😊", genero: 'female' },
  { texto: "certinho!", genero: 'male' },
  { texto: "blz, obg!", genero: 'male' },
  { texto: "to no aguardo", genero: 'male' },
  { texto: "ta certo, to esperando", genero: 'male' },
  { texto: "pode mandar!", genero: 'male' },
  { texto: "manda ai q eu vejo!", genero: 'male' },
  { texto: "to precisando, se puder ir rapido 🙏", genero: 'female' },
  { texto: "se puder mandar rapido, agradeco!", genero: 'male' },
  { texto: "perfeito, to aguardando", genero: 'male' },
  { texto: "show, pode mandar!", genero: 'male' },
  { texto: "me avisa qdo chegar!", genero: 'male' },
  { texto: "obg, to esperando", genero: 'male' },
  { texto: "ta bom, manda", genero: 'male' },
  { texto: "pode enviar, to de olho", genero: 'male' },
  { texto: "beleza, esperando aqui", genero: 'male' },
  { texto: "to precisando pra ja, se puder agilizar!", genero: 'male' },
  { texto: "vou mandar agora, ok", genero: 'male' },
  { texto: "certo, me chama qdo tiver", genero: 'male' },
  { texto: "combinado, to aqui!", genero: 'male' },
];

export const CONFIRMACOES = [
  "sim, sou eu!",
  "isso simm!!",
  "simmmmm",
  "opaaa sou eu sim",
  "sim, participei sim!",
  "sim, eu mesmo!",
  "simm, fui eu",
  "sim sim, sou eu",
  "issoo, eu!!",
  "sim, claro!!",
  "siim, eu tava la",
  "com certeza",
  "sou eu sim!",
  "sim, pode crer",
  "simmmm, eu!",
  "isso, sou eu",
  "sim, tava na live",
  "simm!",
  "sim, opa sou eu",
  "sim sim sim!",
  "claro, sou eu",
  "simm, isso ai",
  "sim, participei",
  "isso memo sou eu",
  "opa, sim sou eu",
  "isso ai, eu!",
  "com certeza sou eu",
  "sim, tava sim",
  "sim, valeu",
  "sim, eu mesmo!",
];

export const RESPOSTAS_AGENUARDAR: { texto: string; faixa: 'baixa' | 'alta'; genero: 'female' | 'male' }[] = [
  // Faixa baixa (50/90) Feminino
  { texto: "obrigada to precisando muito disso", faixa: 'baixa', genero: 'female' },
  { texto: "meu deus obrigada ia ficar sem nada", faixa: 'baixa', genero: 'female' },
  { texto: "obrigada de verdade salvou minha vida", faixa: 'baixa', genero: 'female' },
  { texto: "tava precisando tanto obrigada", faixa: 'baixa', genero: 'female' },
  { texto: "to chorando de tanta gratidao", faixa: 'baixa', genero: 'female' },
  { texto: "obrigadao Deus te pague", faixa: 'baixa', genero: 'female' },
  { texto: "salvou minha semana obrigada", faixa: 'baixa', genero: 'female' },
  { texto: "voce nao imagina o quanto obrigada", faixa: 'baixa', genero: 'female' },
  { texto: "meu deus do ceu obrigada", faixa: 'baixa', genero: 'female' },
  { texto: "to sem palavras de tanta gratidao", faixa: 'baixa', genero: 'female' },
  { texto: "nunca imaginei que isso funcionava", faixa: 'baixa', genero: 'female' },
  { texto: "to tremendo aqui obrigada", faixa: 'baixa', genero: 'female' },
  { texto: "isso e uma bencao na minha vida", faixa: 'baixa', genero: 'female' },
  { texto: "obrigada por acreditar em mim", faixa: 'baixa', genero: 'female' },
  { texto: "vai ajudar muito minha familia", faixa: 'baixa', genero: 'female' },
  // Faixa baixa (50/90) Masculino
  { texto: "vlw ja tava desesperado aqui", faixa: 'baixa', genero: 'male' },
  { texto: "caramba obrigado demais", faixa: 'baixa', genero: 'male' },
  { texto: "n acredito que chegou mesmo", faixa: 'baixa', genero: 'male' },
  { texto: "era oq eu precisava vlw", faixa: 'baixa', genero: 'male' },
  { texto: "tava sem esperança nenhuma", faixa: 'baixa', genero: 'male' },
  { texto: "voce e um anjo mesmo", faixa: 'baixa', genero: 'male' },
  { texto: "obrigado de coracao", faixa: 'baixa', genero: 'male' },
  { texto: "chegou certinho vlw", faixa: 'baixa', genero: 'male' },
  { texto: "isso e vida pra mim", faixa: 'baixa', genero: 'male' },
  { texto: "meu irmao muito obrigado", faixa: 'baixa', genero: 'male' },
  { texto: "chegou na hora certa", faixa: 'baixa', genero: 'male' },
  { texto: "salvou meu dia", faixa: 'baixa', genero: 'male' },
  { texto: "obrigado pela confiança", faixa: 'baixa', genero: 'male' },
  { texto: "isso vai pagar minhas contas", faixa: 'baixa', genero: 'male' },
  { texto: "obrigado msm tava fudido", faixa: 'baixa', genero: 'male' },
  // Faixa alta (150/300) Feminino
  { texto: "caramba eu tava desconfiada mas chegou mesmo", faixa: 'alta', genero: 'female' },
  { texto: "n acreditei quando vi na tela obrigada de verdade", faixa: 'alta', genero: 'female' },
  { texto: "ja tinha caido em golpe antes achei que era mais um", faixa: 'alta', genero: 'female' },
  { texto: "meu deus funcionou mesmo to chocada", faixa: 'alta', genero: 'female' },
  { texto: "pensei que era furada mas chegou certinho", faixa: 'alta', genero: 'female' },
  { texto: "to tremendo aqui achei que ia perder mais dinheiro", faixa: 'alta', genero: 'female' },
  { texto: "ja tinha desistido de acreditar nesse tipo de coisa", faixa: 'alta', genero: 'female' },
  { texto: "chegou mesmo to choquee", faixa: 'alta', genero: 'female' },
  { texto: "obrigada de coracao ja tinha levado golpe antes", faixa: 'alta', genero: 'female' },
  { texto: "não esperava nada e chegou", faixa: 'alta', genero: 'female' },
  { texto: "pensei que era mais um golpe mas funcionou", faixa: 'alta', genero: 'female' },
  { texto: "to sem acreditar chegou mesmo", faixa: 'alta', genero: 'female' },
  { texto: "obrigada demais ja tinha perdido a esperança", faixa: 'alta', genero: 'female' },
  { texto: "chegou certinho obrigada", faixa: 'alta', genero: 'female' },
  { texto: "isso e um milagre obrigada", faixa: 'alta', genero: 'female' },
  // Faixa alta (150/300) Masculino
  { texto: "caramba eu tava desconfiado mas chegou mesmo", faixa: 'alta', genero: 'male' },
  { texto: "n acreditei quando vi na tela obrigado de verdade", faixa: 'alta', genero: 'male' },
  { texto: "ja levei golpe antes achei que era mais um", faixa: 'alta', genero: 'male' },
  { texto: "meu deus funcionou mesmo to chocado", faixa: 'alta', genero: 'male' },
  { texto: "achava que era enganação mas chegou certinho", faixa: 'alta', genero: 'male' },
  { texto: "to tremendo achei que ia perder mais dinheiro", faixa: 'alta', genero: 'male' },
  { texto: "ja tinha largado de mão mas chegou", faixa: 'alta', genero: 'male' },
  { texto: "chegou cara to choquee", faixa: 'alta', genero: 'male' },
  { texto: "obrigado de coracao ja tinha levado golpe antes", faixa: 'alta', genero: 'male' },
  { texto: "não esperava mais nada e chegou", faixa: 'alta', genero: 'male' },
  { texto: "achei que era cilada mas funcionou", faixa: 'alta', genero: 'male' },
  { texto: "to incrédulo chegou mesmo", faixa: 'alta', genero: 'male' },
  { texto: "obrigado demais ja tinha perdido as esperanças", faixa: 'alta', genero: 'male' },
  { texto: "chegou certinho obrigado", faixa: 'alta', genero: 'male' },
  { texto: "isso e um milagre obrigado", faixa: 'alta', genero: 'male' },
];

export const RESPOSTAS_RECEBIMENTO: { texto: string; faixa: 'baixa' | 'alta' }[] = [
  // Faixa baixa (50/90) - gratidão extrema, alívio
  { texto: "chegou!! mt obg, chorei aqui", faixa: 'baixa' },
  { texto: "caiu certinho, obg demais", faixa: 'baixa' },
  { texto: "meu deus chegou, vlw msm", faixa: 'baixa' },
  { texto: "obrigada, ta la sim", faixa: 'baixa' },
  { texto: "chegou, to sem palavras", faixa: 'baixa' },
  { texto: "vlw, salvou minha vida", faixa: 'baixa' },
  { texto: "obg, ia passar fome sem isso", faixa: 'baixa' },
  { texto: "chegou sim, Deus te abençoe", faixa: 'baixa' },
  { texto: "ta la, muito obrigada", faixa: 'baixa' },
  { texto: "recebi, obg de coracao", faixa: 'baixa' },
  { texto: "caramba chegou mesmo, obg", faixa: 'baixa' },
  { texto: "obrigado, vai pagar minhas contas", faixa: 'baixa' },
  // Faixa alta (150/300) - satisfação, quer mais
  { texto: "chegou, show de bola", faixa: 'alta' },
  { texto: "recebi, otimo", faixa: 'alta' },
  { texto: "ta la, certinho", faixa: 'alta' },
  { texto: "chegou, vou investir mais", faixa: 'alta' },
  { texto: "perfeito, caiu rapido", faixa: 'alta' },
  { texto: "obg, cuando tem mais?", faixa: 'alta' },
  { texto: "show, funcionou mesmo", faixa: 'alta' },
  { texto: "chegou, ja quero participar de novo", faixa: 'alta' },
  { texto: "top, valeu a pena", faixa: 'alta' },
  { texto: "otimo, quando tem outro ciclo?", faixa: 'alta' },
  { texto: "beleza, caiu certinho", faixa: 'alta' },
  { texto: "perfeito,to dentro de novo", faixa: 'alta' },
];

// ============ REPETIDO - FLUXO SEPARADO ============

// Mensagens iniciais do repetido (5 por gênero) - avisando que já participou
export const MENSAGENS_REPETIDO_INICIAIS: { texto: string; genero: 'female' | 'male' }[] = [
  // Feminino
  { texto: "moço eu ja participei antes mas mandei [VALOR] no nome de [NOME]", genero: 'female' },
  { texto: "sei que não era pra participar de novo mas fiz o de [VALOR] no nome de [NOME]", genero: 'female' },
  { texto: "oi eu ja fui contemplada mas mandei [VALOR] no nome de [NOME]", genero: 'female' },
  { texto: "moço desculpa mas fiz o pix de [VALOR] no nome de [NOME]", genero: 'female' },
  { texto: "eu sei que ja participei mas mandei [VALOR] no nome de [NOME]", genero: 'female' },
  // Masculino
  { texto: "cara eu ja participei antes mas mandei [VALOR] no nome de [NOME]", genero: 'male' },
  { texto: "sei que não era pra participar de novo mas fiz o de [VALOR] no nome de [NOME]", genero: 'male' },
  { texto: "eu ja fui contemplado mas mandei [VALOR] no nome de [NOME]", genero: 'male' },
  { texto: "cara desculpa mas fiz o pix de [VALOR] no nome de [NOME]", genero: 'male' },
  { texto: "eu sei que ja participei mas mandei [VALOR] no nome de [NOME]", genero: 'male' },
];

// Respostas de espera do repetido (5 por gênero)
export const RESPOSTAS_REPETIDO_ESPERA: { texto: string; genero: 'female' | 'male' }[] = [
  // Feminino
  { texto: "obg to no aguardo", genero: 'female' },
  { texto: "certinho me avisa quando chegar", genero: 'female' },
  { texto: "beleza to esperando", genero: 'female' },
  { texto: "ok combinado", genero: 'female' },
  { texto: "ta certo to de olho", genero: 'female' },
  // Masculino
  { texto: "obg vou ficar de olho", genero: 'male' },
  { texto: "certo me avisa quando tiver", genero: 'male' },
  { texto: "beleza to aguardando", genero: 'male' },
  { texto: "ok ta certo", genero: 'male' },
  { texto: "tranquilo to esperando", genero: 'male' },
];

// Agradecimentos do repetido (5 por gênero) - implorando
export const RESPOSTAS_REPETIDO_AGRADECIMENTO: { texto: string; genero: 'female' | 'male' }[] = [
  // Feminino
  { texto: "poxa que pena quebra essa pra mim eu imploro", genero: 'female' },
  { texto: "moço to passando por um momento muito difícil se puder me ajudar", genero: 'female' },
  { texto: "por favor eu sei que ja participei mas preciso muito dessa ajuda", genero: 'female' },
  { texto: "to desesperada aqui se puder fazer uma exceção eu agradeço", genero: 'female' },
  { texto: "moço eu imploro to sem opção nenhuma", genero: 'female' },
  // Masculino
  { texto: "poxa que pena quebra essa pra mim eu imploro", genero: 'male' },
  { texto: "cara to passando por um momento muito difícil se puder me ajudar", genero: 'male' },
  { texto: "por favor eu sei que ja participei mas preciso muito dessa ajuda", genero: 'male' },
  { texto: "to desesperado aqui se puder fazer uma exceção eu agradeço", genero: 'male' },
  { texto: "cara eu imploro to sem opção nenhuma", genero: 'male' },
];
