export const BRAZILIAN_BANKS = [
  'BANCO DO BRASIL S.A.', 'BANCO BRADESCO S.A.', 'ITAÚ UNIBANCO S.A.', 'CAIXA ECONOMICA FEDERAL', 'BANCO SANTANDER (BRASIL) S.A.',
  'BANCO BTG PACTUAL S.A.', 'BANCO SAFRA S.A.', 'BANCO PAN S.A.', 'BANCO INTER S.A.', 'BANCO C6 S.A.',
  'BANCO MERCANTIL DO BRASIL S.A.', 'BANCO ORIGINAL S.A.', 'BANCO MODAL S.A.', 'BANCO NEON S.A.', 'BANCO BMG S.A.',
  'BANCO XP S.A.', 'BANCO SICOOB S.A.', 'BANCO SICREDI S.A.', 'BANCO DAYCOVAL S.A.', 'BANCO SOFISA S.A.',
  'PICPAY SERVICOS S.A.', 'STONE PAGAMENTOS S.A.', 'MERCADO PAGO INSTITUICAO DE PAGAMENTO LTDA',
  'BANCO RENDIMENTO S.A.', 'BANCO ABC BRASIL S.A.', 'BANCO CREFISA S.A.',
  'BANCO FIBRA S.A.'
];

export const MENSAGENS_INICIAIS: { texto: string; genero: 'female' | 'male' }[] = [
  // Masculino - padrão equalizado para todos os valores
  { texto: "fiz o de [VALOR] ta no nome de [NOME]", genero: 'male' },
  { texto: "mandei [VALOR] agora ta no nome de [NOME]", genero: 'male' },
  { texto: "pronto fiz [VALOR] no nome de [NOME]", genero: 'male' },
  { texto: "ja mandei [VALOR] ta no nome do [NOME]", genero: 'male' },
  { texto: "fiz o de [VALOR] confere no nome de [NOME]", genero: 'male' },
  { texto: "ta feito [VALOR] no nome de [NOME]", genero: 'male' },
  { texto: "mandei [VALOR] pode ver no nome de [NOME]", genero: 'male' },
  { texto: "opa fiz [VALOR] ta no nome de [NOME]", genero: 'male' },
  { texto: "ja ta la [VALOR] no nome de [NOME]", genero: 'male' },
  { texto: "transferi [VALOR] ta no nome de [NOME]", genero: 'male' },
  { texto: "mandei [VALOR] no pix confere la", genero: 'male' },
  { texto: "feito [VALOR] no nome de [NOME]", genero: 'male' },
  { texto: "ja ta la o [VALOR] no nome de [NOME]", genero: 'male' },
  { texto: "enviei [VALOR] no nome de [NOME]", genero: 'male' },
  { texto: "fiz o pix de [VALOR] ta no nome de [NOME]", genero: 'male' },
  // Feminino - padrão equalizado para todos os valores
  { texto: "moço fiz o de [VALOR] ta no nome de [NOME]", genero: 'female' },
  { texto: "oi mandei [VALOR] no nome de [NOME] pode olhar", genero: 'female' },
  { texto: "fiz o pix de [VALOR] ta no nome de [NOME] 🙏", genero: 'female' },
  { texto: "acabei de mandar [VALOR] no nome de [NOME]", genero: 'female' },
  { texto: "enviei [VALOR] agora no nome de [NOME]", genero: 'female' },
  { texto: "moço mandei [VALOR] no nome de [NOME]", genero: 'female' },
  { texto: "ta feito [VALOR] no nome de [NOME] 😊", genero: 'female' },
  { texto: "ja foi [VALOR] no nome de [NOME]", genero: 'female' },
  { texto: "prontinho fiz [VALOR] no nome de [NOME]", genero: 'female' },
  { texto: "mandei [VALOR] rapidinho ta no nome de [NOME]", genero: 'female' },
  { texto: "moço ja ta la [VALOR] no nome de [NOME]", genero: 'female' },
  { texto: "mandei [VALOR] no pix pode conferir", genero: 'female' },
  { texto: "feito [VALOR] no nome de [NOME] 😊", genero: 'female' },
  { texto: "enviei [VALOR] ta no nome de [NOME]", genero: 'female' },
  { texto: "fiz o [VALOR] e ta no nome de [NOME]", genero: 'female' },
];

export const RESPOSTAS_ESPERA: { texto: string; genero: 'female' | 'male' }[] = [
  { texto: "ok, to esperando 😊", genero: 'female' },
  { texto: "certinho!", genero: 'male' },
  { texto: "blz, obg!", genero: 'male' },
  { texto: "to no aguardo", genero: 'male' },
  { texto: "ta certo, to esperando", genero: 'male' },
  { texto: "pode mandar!", genero: 'male' },
  { texto: "manda ai q eu vejo!", genero: 'male' },
  { texto: "to precisando, se puder ir rapido 🙏", genero: 'female' },
  { texto: "se puder mandar rapido, agradeco!", genero: 'male' },
  { texto: "perfeito, to aguardando", genero: 'male' },
  { texto: "show, pode mandar!", genero: 'male' },
  { texto: "me avisa qdo chegar!", genero: 'male' },
  { texto: "obg, to esperando", genero: 'male' },
  { texto: "ta bom, manda", genero: 'male' },
  { texto: "pode enviar, to de olho", genero: 'male' },
  { texto: "beleza, esperando aqui", genero: 'male' },
  { texto: "to precisando pra ja, se puder agilizar!", genero: 'male' },
  { texto: "vou mandar agora, ok", genero: 'male' },
  { texto: "certo, me chama qdo tiver", genero: 'male' },
  { texto: "combinado, to aqui!", genero: 'male' },
];

export const CONFIRMACOES = [
  "sim, sou eu!",
  "isso simm!!",
  "simmmmm",
  "opaaa sou eu sim",
  "sim, participei sim!",
  "sim, eu mesmo!",
  "simm, fui eu",
  "sim sim, sou eu",
  "issoo, eu!!",
  "sim, claro!!",
  "siim, eu tava la",
  "com certeza",
  "sou eu sim!",
  "sim, pode crer",
  "simmmm, eu!",
  "isso, sou eu",
  "sim, tava na live",
  "simm!",
  "sim, opa sou eu",
  "sim sim sim!",
  "claro, sou eu",
  "simm, isso ai",
  "sim, participei",
  "isso memo sou eu",
  "opa, sim sou eu",
  "isso ai, eu!",
  "com certeza sou eu",
  "sim, tava sim",
  "sim, valeu",
  "sim, eu mesmo!",
];

export const RESPOSTAS_AGENUARDAR: { texto: string; faixa: 'baixa' | 'alta' }[] = [
  // Faixa baixa (50/90) - mais desesperada, agradecida
  { texto: "obrigada, to precisando muito disso", faixa: 'baixa' },
  { texto: "vlw, ja tava desesperada aqui", faixa: 'baixa' },
  { texto: "meu deus obg, ia ficar sem nada", faixa: 'baixa' },
  { texto: "obrigado de verdade, salvou", faixa: 'baixa' },
  { texto: "tava precisando tanto, obg", faixa: 'baixa' },
  { texto: "isso vai ajudar demais, obg", faixa: 'baixa' },
  { texto: "obg, to chorando aqui", faixa: 'baixa' },
  { texto: "era oq eu precisava, vlw", faixa: 'baixa' },
  { texto: "obrigadao, Deus te pague", faixa: 'baixa' },
  { texto: "salvou minha semana, obg", faixa: 'baixa' },
  { texto: " caraio obg msm, tava fudido", faixa: 'baixa' },
  { texto: "n acredito, obg de coracao", faixa: 'baixa' },
  // Faixa alta (150/300) - mais confiante, expectante
  { texto: "show, quando cai?", faixa: 'alta' },
  { texto: "beleza, to no aguardo então", faixa: 'alta' },
  { texto: "perfeito, combina assim", faixa: 'alta' },
  { texto: "ok, e quanto eu recebo?", faixa: 'alta' },
  { texto: "top, ja verify que caiu", faixa: 'alta' },
  { texto: "certo, qual o retorno?", faixa: 'alta' },
  { texto: "blz, to esperando o dobro", faixa: 'alta' },
  { texto: "show, quando ta previsto?", faixa: 'alta' },
  { texto: "beleza, vamos nessa", faixa: 'alta' },
  { texto: "perfeito, to confiante", faixa: 'alta' },
  { texto: "ok, bora ver se funciona", faixa: 'alta' },
  { texto: "certinho, to no aguardo", faixa: 'alta' },
];

export const RESPOSTAS_RECEBIMENTO: { texto: string; faixa: 'baixa' | 'alta' }[] = [
  // Faixa baixa (50/90) - gratidão extrema, alívio
  { texto: "chegou!! mt obg, chorei aqui", faixa: 'baixa' },
  { texto: "caiu certinho, obg demais", faixa: 'baixa' },
  { texto: "meu deus chegou, vlw msm", faixa: 'baixa' },
  { texto: "obrigada, ta la sim", faixa: 'baixa' },
  { texto: "chegou, to sem palavras", faixa: 'baixa' },
  { texto: "vlw, salvou minha vida", faixa: 'baixa' },
  { texto: "obg, ia passar fome sem isso", faixa: 'baixa' },
  { texto: "chegou sim, Deus te abençoe", faixa: 'baixa' },
  { texto: "ta la, muito obrigada", faixa: 'baixa' },
  { texto: "recebi, obg de coracao", faixa: 'baixa' },
  { texto: "caramba chegou mesmo, obg", faixa: 'baixa' },
  { texto: "obrigado, vai pagar minhas contas", faixa: 'baixa' },
  // Faixa alta (150/300) - satisfação, quer mais
  { texto: "chegou, show de bola", faixa: 'alta' },
  { texto: "recebi, otimo", faixa: 'alta' },
  { texto: "ta la, certinho", faixa: 'alta' },
  { texto: "chegou, vou investir mais", faixa: 'alta' },
  { texto: "perfeito, caiu rapido", faixa: 'alta' },
  { texto: "obg, cuando tem mais?", faixa: 'alta' },
  { texto: "show, funcionou mesmo", faixa: 'alta' },
  { texto: "chegou, ja quero participar de novo", faixa: 'alta' },
  { texto: "top, valeu a pena", faixa: 'alta' },
  { texto: "otimo, quando tem outro ciclo?", faixa: 'alta' },
  { texto: "beleza, caiu certinho", faixa: 'alta' },
  { texto: "perfeito,to dentro de novo", faixa: 'alta' },
];
