export const BRAZILIAN_BANKS = [
  'BANCO DO BRASIL S.A.', 'BANCO BRADESCO S.A.', 'ITAÚ UNIBANCO S.A.', 'CAIXA ECONOMICA FEDERAL', 'BANCO SANTANDER (BRASIL) S.A.',
  'BANCO BTG PACTUAL S.A.', 'BANCO SAFRA S.A.', 'BANCO PAN S.A.', 'BANCO INTER S.A.', 'BANCO C6 S.A.',
  'BANCO MERCANTIL DO BRASIL S.A.', 'BANCO ORIGINAL S.A.', 'BANCO MODAL S.A.', 'BANCO NEON S.A.', 'BANCO BMG S.A.',
  'BANCO XP S.A.', 'BANCO SICOOB S.A.', 'BANCO SICREDI S.A.', 'BANCO DAYCOVAL S.A.', 'BANCO SOFISA S.A.',
  'PICPAY SERVICOS S.A.', 'STONE PAGAMENTOS S.A.', 'MERCADO PAGO INSTITUICAO DE PAGAMENTO LTDA',
  'BANCO RENDIMENTO S.A.', 'BANCO ABC BRASIL S.A.', 'BANCO CREFISA S.A.',
  'BANCO FIBRA S.A.'
];

export const MENSAGENS_INICIAIS: { texto: string; genero: 'female' | 'male' }[] = [
  { texto: "acabei de mandar [MESES] [MESES_TEXTO] la, ta no nome do [NOME] 😊", genero: 'female' },
  { texto: "mandei agora [MESES] [MESES_TEXTO], pode conferir no nome do [NOME]", genero: 'male' },
  { texto: "mandei [MESES] [MESES_TEXTO], ta no nome do [NOME] ✅", genero: 'female' },
  { texto: "pronto, acabei de mandar [MESES] [MESES_TEXTO]! ta no nome do [NOME]", genero: 'male' },
  { texto: "enviei [MESES] [MESES_TEXTO] agora, ta no nome do [NOME]", genero: 'male' },
  { texto: "ja ta la, mandei [MESES] [MESES_TEXTO] no nome do [NOME]!", genero: 'male' },
  { texto: "fiz o envio de [MESES] [MESES_TEXTO], ta no nome do [NOME]", genero: 'male' },
  { texto: "mandei [MESES] [MESES_TEXTO], ta no nome do [NOME]", genero: 'male' },
  { texto: "acabei de mandar [MESES] [MESES_TEXTO] o comprovante, ta no nome do [NOME]", genero: 'male' },
  { texto: "transferi [MESES] [MESES_TEXTO], pode ver no nome do [NOME]", genero: 'male' },
  { texto: "ja enviei [MESES] [MESES_TEXTO], ta no nome do [NOME]!", genero: 'male' },
  { texto: "prontinho, mandei [MESES] [MESES_TEXTO] no nome do [NOME]", genero: 'female' },
  { texto: "ta feito! mandei [MESES] [MESES_TEXTO] no nome do [NOME]", genero: 'male' },
  { texto: "acabei de fazer o envio de [MESES] [MESES_TEXTO], ta no nome do [NOME]", genero: 'male' },
  { texto: "enviei [MESES] [MESES_TEXTO] rapidinho, ta no nome do [NOME]", genero: 'female' },
  { texto: "ja foi [MESES] [MESES_TEXTO], ta no nome do [NOME]!", genero: 'male' },
  { texto: "acabei de mandar [MESES] [MESES_TEXTO] direitinho, ta no nome do [NOME]", genero: 'female' },
  { texto: "mandei [MESES] [MESES_TEXTO] agora, pode conferir: ta no nome do [NOME]", genero: 'male' },
  { texto: "ta la! mandei [MESES] [MESES_TEXTO] no nome do [NOME] 👌", genero: 'female' },
  { texto: "acabei de mandar [MESES] [MESES_TEXTO], confere la no nome do [NOME]", genero: 'male' },
  { texto: "mandei poucos meses la, ta no nome do [NOME] 😊", genero: 'female' },
  { texto: "enviei uns poucos meses, pode ver no nome do [NOME]", genero: 'male' },
  { texto: "ja mandei, foram uns poucos meses no nome do [NOME]!", genero: 'male' },
  { texto: "acabei de mandar alguns meses, ta no nome do [NOME]", genero: 'female' },
  { texto: "mandei alguns meses agora, ta no nome do [NOME] ✅", genero: 'female' },
  { texto: "ta la, mandei uns raros meses no nome do [NOME]!", genero: 'male' },
  { texto: "mandei raros meses, confere no nome do [NOME]", genero: 'male' },
  { texto: "acabei de mandar uns raros meses, ta no nome do [NOME]", genero: 'female' },
  { texto: "enviei uns meses la, ta no nome do [NOME]", genero: 'male' },
  { texto: "ja foram uns meses, mandei no nome do [NOME]!", genero: 'male' },
];

export const RESPOSTAS_ESPERA: { texto: string; genero: 'female' | 'male' }[] = [
  { texto: "ok, to esperando 😊", genero: 'female' },
  { texto: "certinho!", genero: 'male' },
  { texto: "blz, obg!", genero: 'male' },
  { texto: "to no aguardo", genero: 'male' },
  { texto: "ta certo, to esperando", genero: 'male' },
  { texto: "pode mandar!", genero: 'male' },
  { texto: "manda ai q eu vejo!", genero: 'male' },
  { texto: "to precisando, se puder ir rapido 🙏", genero: 'female' },
  { texto: "se puder mandar rapido, agradeco!", genero: 'male' },
  { texto: "perfeito, to aguardando", genero: 'male' },
  { texto: "show, pode mandar!", genero: 'male' },
  { texto: "me avisa qdo chegar!", genero: 'male' },
  { texto: "obg, to esperando", genero: 'male' },
  { texto: "ta bom, manda", genero: 'male' },
  { texto: "pode enviar, to de olho", genero: 'male' },
  { texto: "beleza, esperando aqui", genero: 'male' },
  { texto: "to precisando pra ja, se puder agilizar!", genero: 'male' },
  { texto: "vou mandar agora, ok", genero: 'male' },
  { texto: "certo, me chama qdo tiver", genero: 'male' },
  { texto: "combinado, to aqui!", genero: 'male' },
];

export const CONFIRMACOES = [
  "sim, sou eu!",
  "isso simm!!",
  "simmmmm",
  "opaaa sou eu sim",
  "sim, participei sim!",
  "sim, eu mesmo!",
  "simm, fui eu",
  "sim sim, sou eu",
  "issoo, eu!!",
  "sim, claro!!",
  "siim, eu tava la",
  "com certeza",
  "sou eu sim!",
  "sim, pode crer",
  "simmmm, eu!",
  "isso, sou eu",
  "sim, tava na live",
  "simm!",
  "sim, opa sou eu",
  "sim sim sim!",
  "claro, sou eu",
  "simm, isso ai",
  "sim, participei",
  "isso memo sou eu",
  "opa, sim sou eu",
  "isso ai, eu!",
  "com certeza sou eu",
  "sim, tava sim",
  "sim, valeu",
  "sim, eu mesmo!",
];

export const RESPOSTAS_MESES = [
  "vlw mesmo, chegou certinho",
  "obrigado, chegou sim",
  "chegou sim, obgd",
  "valeu, ta la",
  "brigadao, chegou",
  "so gratidao, obgd",
  "obrigadao, certinho",
  "Deus te abençoe, chegou",
  "valeu demais, ta la",
  "so sucesso, chegou sim",
  "pode crer, ta la",
  "tmj, obgd",
  "obrigado de coracao",
  "paz e bencaos, chegou",
  "Deus te pague",
  "muito obrigado, certinho",
  "agradeco demais, ta la",
  "top demais, chegou sim",
  "que isso fera, obgd",
  "obrigado demais",
  "mano chegou na hora, valeu",
  "que isso voce e sensacional, obgd",
  "salvou minha semana, chegou",
  "obrigado demais, vai ajudar muito",
  "cara salvou meu dia, ta la",
  "to sem palavras, obgd",
  "manda bem demais, chegou",
  "era oq tava precisando, certinho",
  "n acredito que caiu",
  "vlw mesmo, tava precisando",
  "resolvido aqui, caiu certinho, to muito grato",
  "Deus te pague tudo",
  "caralho real? valeu",
  "que tipo de anjo e voce",
  "obrigadao, paga meu lanche",
  "so gratidao mesmo",
  "voce nao imagina o quanto tava precisando",
  "salvou minha familia, chegou",
  "nunca vi isso, achava que era brincadeira",
  "obrigado demais, vai dar pra pagar aquela conta",
  "meu deus mano e serio? salvou demais",
  "putz mano voce salvou minha vida",
  "esse valor vai fazer diferenca, muito obg",
  "cara eu tava prestes a ser despejado, nao to acreditando",
  "obrigado mano muda tudo aqui em casa",
  "to tremendo, caiu de verdade",
  "voce e diferenciado, Deus te abençoe",
  "isso aqui paga minhas contas",
  "caramba tu e brabo",
  "to chorando mano, obgd",
  "pode crer que vicio em bondade",
];